[project]
name = "depths-of-python"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "ipykernel>=6.29.5",
    "notebook>=7.4.0",
    "objgraph>=3.6.2",
    "pandas>=2.2.3",
]
